/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        sage: { 50: '#faf9f6', 100: '#f4f4f0', 200: '#eeeeea', 300: '#e3e3df', 400: '#c2c8c1', 500: '#727972', 600: '#476550', 700: '#375541', 800: '#304d3a', 900: '#1a1c1a' },
        sand: { 50: '#fffdfa', 100: '#f6f0e7', 200: '#e8dccb', 300: '#d6c2ab', 400: '#bea082', 500: '#a98566', 600: '#8a6a52', 700: '#705544', 800: '#574236', 900: '#43322a' },
        clay: { 50: '#fff6f4', 100: '#ffdad6', 200: '#f7b8b1', 300: '#ee8f85', 400: '#e16a60', 500: '#c94d46', 600: '#ba1a1a', 700: '#93000a', 800: '#76110f', 900: '#5d100f' },
        moss: { 50: '#f4f7f3', 100: '#d9e6d9', 200: '#c9ebd1', 300: '#bdcabd', 400: '#aecfb5', 500: '#5c675d', 600: '#566157', 700: '#3e4a40', 800: '#324c3d', 900: '#131e16' },
        'primary-container': '#4f6d58',
        'on-tertiary-fixed-variant': '#324c3d',
        'inverse-on-surface': '#f1f1ed',
        'surface-container-high': '#e9e8e5',
        'primary-fixed': '#c9ebd1',
        error: '#ba1a1a',
        'primary-fixed-dim': '#aecfb5',
        'on-error-container': '#93000a',
        'on-surface-variant': '#424843',
        'surface-container': '#eeeeea',
        'on-error': '#ffffff',
        'surface-tint': '#476550',
        'secondary-fixed': '#d9e6d9',
        'surface-variant': '#e3e3df',
        tertiary: '#395444',
        'on-secondary-container': '#5c675d',
        'secondary-fixed-dim': '#bdcabd',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#304d3a',
        'on-primary-container': '#ccedd3',
        'tertiary-fixed-dim': '#afceb9',
        'inverse-primary': '#aecfb5',
        'surface-bright': '#faf9f6',
        'on-secondary-fixed-variant': '#3e4a40',
        'on-primary-fixed': '#032111',
        primary: '#375541',
        'outline-variant': '#c2c8c1',
        'on-tertiary-fixed': '#052013',
        'inverse-surface': '#2f312f',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e3e3df',
        'on-background': '#1a1c1a',
        'on-tertiary-container': '#cdecd7',
        'on-secondary-fixed': '#131e16',
        secondary: '#566157',
        'on-secondary': '#ffffff',
        'on-surface': '#1a1c1a',
        'error-container': '#ffdad6',
        background: '#faf9f6',
        'surface-dim': '#dadad7',
        'tertiary-fixed': '#cbead5',
        'tertiary-container': '#506c5b',
        'surface-container-low': '#f4f4f0',
        surface: '#faf9f6',
        'secondary-container': '#d9e6d9',
        outline: '#727972',
      },
      fontFamily: {
        display: ['"EB Garamond"', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        ui: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        'display-lg-mobile': ['"EB Garamond"', 'serif'],
        metadata: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        'label-md': ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['"EB Garamond"', 'serif'],
        'headline-sm': ['"EB Garamond"', 'serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['"EB Garamond"', 'serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        'serif-display': ['"EB Garamond"', 'serif'],
      },
      borderRadius: {
        '4xl': '1.5rem',
        '5xl': '2rem',
        button: '24px',
        card: '24px',
      },
      spacing: {
        'stack-md': '24px',
        gutter: '24px',
        'container-padding-mobile': '24px',
        'section-gap': '80px',
        'stack-sm': '8px',
        'container-padding-desktop': '64px',
        unit: '8px',
        'stack-lg': '48px',
      },
      fontSize: {
        'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '500' }],
        metadata: ['11px', { lineHeight: '1.5', letterSpacing: '0.05em', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        soft: '0 24px 60px -36px rgba(26, 28, 26, 0.16)',
        lifted: '0 36px 80px -42px rgba(26, 28, 26, 0.24)',
        'inner-soft': 'inset 0 1px 0 rgba(255,255,255,0.7)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'fade-in-up': 'fadeInUp 0.9s ease-out',
        'slide-up': 'slideUp 0.5s cubic-bezier(0.22, 1, 0.36, 1)',
        'scale-in': 'scaleIn 0.35s ease-out',
        float: 'float 8s ease-in-out infinite',
        shimmer: 'shimmer 1.5s linear infinite',
        drift: 'drift 18s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeInUp: { from: { transform: 'translateY(18px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        slideUp: { from: { transform: 'translateY(18px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        scaleIn: { from: { transform: 'scale(0.96)', opacity: '0' }, to: { transform: 'scale(1)', opacity: '1' } },
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        shimmer: { '0%': { backgroundPosition: '-1000px 0' }, '100%': { backgroundPosition: '1000px 0' } },
        drift: { '0%,100%': { transform: 'translate3d(0, 0, 0) scale(1)' }, '50%': { transform: 'translate3d(0, -12px, 0) scale(1.02)' } },
      },
    },
  },
  plugins: [],
};
